# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -Djava.awt.headless=true -B install --file pom.xml

    - name: Archive JAR artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Engine Alpha Bibliotheken
        path: |
          engine-alpha/target/engine-alpha-4-jar-with-dependencies.jar
          engine-alpha-edu/target/engine-alpha-4-edu-jar-with-dependencies.jar

    - name: Build documentation with Maven
      run: mvn -Djava.awt.headless=true -B site --file pom.xml

    - name: Archive Engine Alpha documentation
      uses: actions/upload-artifact@v3
      with:
        name: Engine Alpha Dokumentation
        path: |
          engine-alpha/target/site/apidocs/

    - name: Archive Engine Alpha EDU documentation
      uses: actions/upload-artifact@v3
      with:
        name: Engine Alpha EDU Dokumentation
        path: |
          engine-alpha-edu/target/site/apidocs/
